## Build the lazy-loaded datasets shipped with the package from the proportion
## CSVs at the repo root (one level up from this package). Re-run whenever the
## CSVs are regenerated by `python3 generate_race_proportions.py` or by
## `python3 rosenman_olivella_imai_2023/generate_proportions_csvs.py`.
##
## Outputs five data objects:
##   first_names         - 53,615 rows, one per first name (Census 2020)
##   last_names          - 156,619 rows, one per last name  (Census 2020)
##   first_names_sex     - 53,615 rows, one per first name (M/F probabilities)
##   first_names_extra   - 85,213 voter-file first names not in Census 2020
##                          (Rosenman, Olivella, and Imai 2023, expanded to the same
##                          6 race columns as `first_names`)
##   last_names_extra    - 195,571 voter-file last names not in Census 2020
##                          (Rosenman, Olivella, and Imai 2023, expanded to the same
##                          6 race columns as `last_names`)
##
## Each table also has an attached "prior" attribute: the marginal proportion
## of each group across the full population, computed by weighting each row's
## proportions by FREQUENCY (COUNT) and including the trailing
## "ALL OTHER NAMES" row that the per-name lookup excludes. The `_extra`
## tables inherit the corresponding Census prior (Rosenman publishes only
## conditional probabilities, no name-level frequencies).

suppressPackageStartupMessages({
  library(readr)
})

repo_root <- normalizePath(file.path("..", "..", ".."), mustWork = TRUE)
pkg_root  <- normalizePath(file.path(".."),               mustWork = TRUE)

read_proportions <- function(path, prop_cols, prop_names) {
  df <- readr::read_csv(
    path,
    col_types = readr::cols(.default = readr::col_character())
  )
  out <- data.frame(
    name      = toupper(trimws(df[[1]])),
    frequency = suppressWarnings(as.integer(df[[3]])),
    stringsAsFactors = FALSE
  )
  for (i in seq_along(prop_cols)) {
    out[[prop_names[i]]] <- suppressWarnings(as.numeric(df[[prop_cols[i]]]))
  }
  out
}

compute_prior <- function(df, prop_names) {
  freq <- df$frequency
  ok   <- is.finite(freq) & freq > 0
  totals <- vapply(prop_names, function(g) {
    p <- df[[g]][ok]
    sum(p * freq[ok], na.rm = TRUE)
  }, numeric(1))
  totals / sum(freq[ok], na.rm = TRUE)
}

split_lookup_and_other <- function(df) {
  is_other <- df$name == "ALL OTHER NAMES"
  list(lookup = df[!is_other, , drop = FALSE], other = df[is_other, , drop = FALSE])
}

RACE_NAMES <- c("white", "black", "aian", "aapi", "nh_multi", "hispanic")
SEX_NAMES  <- c("male", "female")

message("Reading first names (race/Hispanic origin) ...")
first_raw <- read_proportions(
  file.path(repo_root, "Names2020_FirstNames_RaceHispanic_Proportions.csv"),
  prop_cols  = 6:11,
  prop_names = RACE_NAMES
)
first_split <- split_lookup_and_other(first_raw)
first_names <- first_split$lookup
attr(first_names, "prior") <- compute_prior(first_raw, RACE_NAMES)
attr(first_names, "groups") <- RACE_NAMES

message("Reading last names (race/Hispanic origin) ...")
last_raw <- read_proportions(
  file.path(repo_root, "Names2020_LastNames_RaceHispanic_Proportions.csv"),
  prop_cols  = 6:11,
  prop_names = RACE_NAMES
)
last_split <- split_lookup_and_other(last_raw)
last_names <- last_split$lookup
attr(last_names, "prior") <- compute_prior(last_raw, RACE_NAMES)
attr(last_names, "groups") <- RACE_NAMES

message("Reading first names (sex) ...")
sex_raw <- read_proportions(
  file.path(repo_root, "Names2020_FirstNames_Sex_Proportions.csv"),
  prop_cols  = 6:7,
  prop_names = SEX_NAMES
)
sex_split <- split_lookup_and_other(sex_raw)
first_names_sex <- sex_split$lookup
attr(first_names_sex, "prior") <- compute_prior(sex_raw, SEX_NAMES)
attr(first_names_sex, "groups") <- SEX_NAMES

## Rosenman, Olivella, and Imai (2023) voter-file additions for names not present
## in the 2020 Census tabulation. Source CSVs ship 5 race columns where
## "OTHER" lumps AIAN, two-or-more, and other; we split that bucket back
## into AIAN and nh_multi proportionally to the corresponding Census prior
## so the resulting rows have the same 6 columns as the Census tables and
## can feed the same Naive-Bayes combination unchanged.
read_rosenman_extra <- function(path) {
  df <- readr::read_csv(
    path,
    col_types = readr::cols(.default = readr::col_character()),
    na = character()  # preserve any literal "NA" / "NULL" surnames
  )
  data.frame(
    name     = toupper(trimws(df[[1]])),
    white    = suppressWarnings(as.numeric(df[[2]])),
    black    = suppressWarnings(as.numeric(df[[3]])),
    aapi     = suppressWarnings(as.numeric(df[[4]])),
    other    = suppressWarnings(as.numeric(df[[5]])),
    hispanic = suppressWarnings(as.numeric(df[[6]])),
    stringsAsFactors = FALSE
  )
}

expand_other_to_aian_nh_multi <- function(df, prior) {
  share_aian <- unname(prior["aian"]) /
    (unname(prior["aian"]) + unname(prior["nh_multi"]))
  out <- data.frame(
    name      = df$name,
    frequency = NA_integer_,
    white     = df$white,
    black     = df$black,
    aian      = df$other * share_aian,
    aapi      = df$aapi,
    nh_multi  = df$other * (1 - share_aian),
    hispanic  = df$hispanic,
    stringsAsFactors = FALSE
  )
  out
}

rosenman_dir <- file.path(repo_root, "rosenman_olivella_imai_2023")

## Use the last_names prior for both extras: it is the canonical Naive-Bayes
## prior used by `combine_bayes_n()` throughout the package, and matches the
## prior used by the JS port at runtime (it expands Rosenman in-browser using
## the loaded last_names prior). Keeping a single prior across R and JS avoids
## tiny per-row inconsistencies between the two implementations.
extra_prior <- attr(last_names, "prior")

message("Reading Rosenman first names (NotInCensus2020) ...")
first_extra_raw <- read_rosenman_extra(
  file.path(rosenman_dir, "RosenmanOlivellaImai2023_FirstNames_NotInCensus2020.csv")
)
first_names_extra <- expand_other_to_aian_nh_multi(first_extra_raw, extra_prior)
attr(first_names_extra, "prior")  <- extra_prior
attr(first_names_extra, "groups") <- RACE_NAMES
attr(first_names_extra, "source") <- "rosenman_olivella_imai_2023"

message("Reading Rosenman last names (NotInCensus2020) ...")
last_extra_raw <- read_rosenman_extra(
  file.path(rosenman_dir, "RosenmanOlivellaImai2023_LastNames_NotInCensus2020.csv")
)
last_names_extra <- expand_other_to_aian_nh_multi(last_extra_raw, extra_prior)
attr(last_names_extra, "prior")  <- extra_prior
attr(last_names_extra, "groups") <- RACE_NAMES
attr(last_names_extra, "source") <- "rosenman_olivella_imai_2023"

data_dir <- file.path(pkg_root, "data")
dir.create(data_dir, showWarnings = FALSE, recursive = TRUE)

message("Saving .rda files (xz compression) ...")
save(first_names,        file = file.path(data_dir, "first_names.rda"),        compress = "xz")
save(last_names,         file = file.path(data_dir, "last_names.rda"),         compress = "xz")
save(first_names_sex,    file = file.path(data_dir, "first_names_sex.rda"),    compress = "xz")
save(first_names_extra,  file = file.path(data_dir, "first_names_extra.rda"),  compress = "xz")
save(last_names_extra,   file = file.path(data_dir, "last_names_extra.rda"),   compress = "xz")

message(sprintf(
  paste("Done.",
        "first_names: %d | last_names: %d | first_names_sex: %d |",
        "first_names_extra: %d | last_names_extra: %d"),
  nrow(first_names), nrow(last_names), nrow(first_names_sex),
  nrow(first_names_extra), nrow(last_names_extra)
))
